[homie]
device_id="mijia-bridge"
device_name="Mijia bridge"
prefix="homie"
sensor_names_filename="sensor-names.toml"

[mqtt]
host="test.mosquitto.org"
port=1883
client_name="mijia-bridge"
# username=""
# password=""
# use_tls=true
