[package]
name = "mijia"
version = "0.1.0"
authors = ["Luis Félix <lcs.felix@gmail.com>", "Andrew Walbran <qwandor@google.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
bluez-generated = { path = "../bluez-generated" }
dbus = {version = "0.8.4", features = ["futures"]}
itertools = "*"
anyhow = "*"
dbus-tokio = "*"
tokio = "0.2.22"
futures = "0.3"
