[package]
name = "bluez-generated"
version = "0.1.0"
authors = ["Andrew Walbran <qwandor@google.com>", "David Laban <alsuren@gmail.com>"]
edition = "2018"

[dependencies]
dbus = { version = "0.8.4", features = ["futures"] }
